#!/bin/sh

# PROVIDE: FedoraShare
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# FedoraShare_enable (bool): Set to NO by default. Set this variable to YES if you want to enable FedoraShare service.
# FedoraShare_config (path): Set to /usr/local/etc/FedoraShare.conf by default.
# FedoraShare_user:  The user account FedoraShare daemon runs as. It uses 'root' user by default.
# FedoraShare_group: The group account FedoraShare daemon runs as. It uses 'wheel' group by default.
# FedoraShare_datadir (str): Default to "/var/db/FedoraShare". Base data directory.

. /etc/rc.subr

name=FedoraShare
rcvar=FedoraShare_enable

: ${FedoraShare_enable:=NO}
: ${FedoraShare_config=/usr/local/etc/FedoraShare.conf}
: ${FedoraShare_datadir=/var/db/FedoraShare}
: ${FedoraShare_user="root"}
: ${FedoraShare_group="wheel"}

required_files=${FedoraShare_config}
command=/usr/local/bin/FedoraShared
FedoraShare_chdir=${FedoraShare_datadir}
pidfile="${FedoraShare_datadir}/FedoraShared.pid"
stop_cmd=FedoraShare_stop
command_args="-conf=${FedoraShare_config} -datadir=${FedoraShare_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

FedoraShare_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${FedoraShare_datadir}
	[ $? -eq 0 ] && chown -R ${FedoraShare_user}:${FedoraShare_group} ${FedoraShare_datadir}
}

FedoraShare_prestart()
{
	if [ ! -d "${FedoraShare_datadir}/." ]; then
		FedoraShare_create_datadir || return 1
	fi
}

FedoraShare_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

FedoraShare_stop()
{
    FedoraShare_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${FedoraShare_config} -datadir=${FedoraShare_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
